/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Mon Sep 19 2016 16:42:11 GMT+0200 (CEST)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
exports.ENV = {};
//# sourceMappingURL=env.js.map